<?php
/**
 * @file
 * product_pages.features.inc
 */

/**
 * Implements hook_views_api().
 */
function product_pages_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function product_pages_node_info() {
  $items = array(
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use <em>basic pages</em> for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'product_detail_page' => array(
      'name' => t('Product Detail Page'),
      'base' => 'node_content',
      'description' => t('Create a page to display the details for a specific product'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
